### ISSUE TITLE
Pods always pending

### ISSUE THREAD

**Issue by seniorquico** [SaladTechnologies/virtual-kubelet-saladcloud#137]
### What actually happened?

After creating a deployment, the pods were correctly started up as SaladCloud container group deployments. However, the status of the pod in the K8s cluster remained "Pending". Even after the startup, liveness, and readiness probes succeeded, the status of the pod remained "Pending".

![Image](https://github.com/user-attachments/assets/3debf3c3-9b59-4699-ab39-62f359d7a58b)

### What did you expect to happen?

The status of the pod should change as the container group moves through its allocating, downloading, creating, and running states.

### How can we reproduce it?

Create a simple deployment, like the following, and observe the status of the pods.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-deployment
  labels:
    app: terminal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      annotations:
        salad.com/country-codes: ca
        salad.com/gpu-classes: "f51baccc-dc95-40fb-a5d1-6d0ee0db31d2,69071b6c-3d2c-4181-b3ce-de03aec04b9f,cb6c1931-89b6-4f76-976f-54047320ccc6"
      labels:
        app: terminal
    spec:
      containers:
        - env:
            - name: GREETING
              value: "Hello, Salad!"
          image: ghcr.io/saladtechnologies/recipe-base-ubuntu:0.1
          livenessProbe:
            exec:
              command: ["cat", "/healthy"]
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 15
          name: ubuntu
          readinessProbe:
            exec:
              command: ["cat", "/healthy"]
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
          startupProbe:
            exec:
              command: ["cat", "/healthy"]
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 15
      nodeSelector:
        kubernetes.io/role: agent
        type: virtual-kubelet
      os:
        name: linux
      restartPolicy: Always
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Equal
          value: saladcloud
          effect: NoSchedule
```

### What is the version of your SaladCloud Virtual Kubelet?

I used a local build of the latest commit on the main branch (at the time of writing), commit SaladTechnologies/virtual-kubelet-saladcloud@06ecaaf.

### What is the version of your Kubernetes cluster?

1.31.4
