### ISSUE TITLE
Error when deploy through ArgoCD

### ISSUE THREAD

**Issue by Artem3213212** [SaladTechnologies/virtual-kubelet-saladcloud#84]
### What actually happened?

Error:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): failed to set app instance tracking info on manifest: failed to set app instance label: failed to get labels from target object /v1, Kind=ServiceAccount default/salad-init-settings-deploy-virtual-kubelet-saladcloud-provider: .metadata.labels accessor error: contains non-string value in the map under key "app.kubernetes.io/version": <nil> is of the type <nil>, expected string
```

ArgoCD Application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: salad-init-settings-deploy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: https://kubernetes.default.svc
  sources:
    - path: charts/virtual-kubelet
      repoURL: https://github.com/SaladTechnologies/virtual-kubelet-saladcloud.git
      targetRevision: main
      helm:
        valuesObject:
          salad:
            apiKey: ***
            organizationName: ***
            projectName: ***
  syncPolicy:
    automated: {}
    syncOptions: # Sync options which modifies sync behavior
      - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
  revisionHistoryLimit: 10
```

### What did you expect to happen?

ArgoCD deploy application

### How can we reproduce it?

Deploy ArgoCD, and apply Application manifest I gived above.

### Anything else we should know?

Under hood ArgoCD used `helm template ...` comand (It render results to file instead of applying them to cluster). I think problem may related with this.

### What is the version of your SaladCloud Virtual Kubelet Provider?

main branch

### What is the version of your Kubernetes cluster?

1.29
